"""add available column to products

Revision ID: 2116a771b4e2
Revises: 9ed05806f8d0
Create Date: 2026-06-26 17:06:09.975916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2116a771b4e2'
down_revision: Union[str, Sequence[str], None] = '9ed05806f8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('available', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'available')
    # ### end Alembic commands ###
